### ISSUE TITLE
Prevent Page Reload

### ISSUE THREAD

**Issue by jimbuck** [kc5nra/CLRBrowserSourcePlugin#1]
Is there any way to disable the page refresh when toggling sources or changing scenes?

**Comment by Jack0r** [comment]
Add the Browser as a Global Source to your scene in OBS.

**Comment by jimbuck** [comment]
@Jack0r Thanks, that does the trick!

**Comment by jimbuck** [comment]
@Jack0r Any way to mute a global source when toggled in a scene?
