### ISSUE TITLE
Add support for navigator.getUserMedia()

### ISSUE THREAD

**Issue by SK83RJOSH** [kc5nra/CLRBrowserSourcePlugin#2]
This is probably a bit of an odd request, but there's a few things that would benefit greatly if you were to update chromium to expose this some how.

Not 100% sure how feasible it is though, since it prompts the user to enable access..

**Comment by kc5nra** [comment]
If you search the thread you can actually find an example of using this.  I
added support for custom command line options that allow you to skip the
auth check

On Saturday, February 21, 2015, Joshua Wood notifications@github.com
wrote:

> This is probably a bit of an odd request, but there's a few things that
> would benefit greatly if you were to update chromium to expose this some
> how.
> 
> Not 100% sure how feasible it is though, since it prompts the user to
> enable access usually..
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kc5nra/CLRBrowserSourcePlugin/issues/2.

## 

John R. Bradley
Turret Technology, LLC

(+1) 512-568-1665 (Voice)
(+1) 512-692-6198 (Fax)
jrb@turrettech.com

**Comment by SK83RJOSH** [comment]
Oh I see, my apologies!
